version: 0.2

phases:
  install:
    commands:
      - python3 -m venv .env
      - source .env/bin/activate
      - pip install -r requirements.txt
      - npm install -g aws-cdk
  build:
    commands:
      - echo "Deploy started on `date`"
      - cdk deploy
